locale = "de"
label = "Deutsch"
weight = 2
title = "KingShip"

[params]
  displayName = "Deutsch"
  isoCode = "de"
  rtl = false
  dateFormat = "2. January 2006"
  logo = ""
  description = "Professionelle Präzisions-Aluminium- und Magnesium-Druckguss-Dienstleistungen"

[params.author]
  name = "KingShip"
  email = ""
  image = ""
  headline = ""
  bio = ""
  links = []
