locale = "en"
label = "English"
weight = 1
title = "KingShip"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = ""
  description = "Professional Precision Aluminum & Magnesium Die Casting Services"

[params.author]
  name = "KingShip"
  email = ""
  image = ""
  headline = ""
  bio = ""
  links = []