[[main]]
  name = "Startseite"
  url = "/"
  weight = 10

[[main]]
  name = "Aluminium-Druckguss"
  url = "/de/aluminum-die-casting/"
  weight = 20

[[main]]
  name = "Magnesium-Druckguss"
  url = "/de/magnesium-die-casting/"
  weight = 30

[[main]]
  name = "Technischer Blog"
  url = "/de/blog/"
  weight = 40

[[main]]
  name = "Tags"
  url = "/de/tags/"
  weight = 45

[[main]]
  name = "Angebot anfragen"
  url = "/de/contact/"
  weight = 50