[[main]]
  name = "ホーム"
  url = "/ja/"
  weight = 10

[[main]]
  name = "アルミダイカスト"
  url = "/ja/aluminum-die-casting/"
  weight = 20

[[main]]
  name = "マグネシウムダイカスト"
  url = "/ja/magnesium-die-casting/"
  weight = 30

[[main]]
  name = "技術ブログ"
  url = "/ja/blog/"
  weight = 40

[[main]]
  name = "タグ"
  url = "/ja/tags/"
  weight = 45

[[main]]
  name = "見積依頼"
  url = "/ja/contact/"
  weight = 50
