[[main]]
  name = "Startseite"
  url = "/"
  weight = 10

[[main]]
  name = "Aluminium-Druckguss"
  url = "/de/aluminum-die-casting/"
  weight = 20

[[main]]
  name = "Magnesium-Druckguss"
  url = "/de/magnesium-die-casting/"
  weight = 30

[[main]]
  name = "Semi-Solid-Rheocasting"
  url = "/de/semi-solid-rheocasting/"
  weight = 32

[[main]]
  name = "CNC-Bearbeitung"
  url = "/de/cnc-machining/"
  weight = 34

[[main]]
  name = "Werkzeugbau"
  url = "/de/tooling/"
  weight = 36

[[main]]
  name = "Technischer Blog"
  url = "/de/blog/"
  weight = 40

[[main]]
  name = "Angebot anfragen"
  url = "/de/contact/"
  weight = 50
