[[main]]
  name = "Home"
  url = "/"
  weight = 10

[[main]]
  name = "Aluminum Die Casting"
  url = "/aluminum-die-casting/"
  weight = 20

[[main]]
  name = "Magnesium Die Casting"
  url = "/magnesium-die-casting/"
  weight = 30

[[main]]
  name = "Semi-Solid Rheocasting"
  url = "/semi-solid-rheocasting/"
  weight = 32

[[main]]
  name = "CNC Machining"
  url = "/cnc-machining/"
  weight = 34

[[main]]
  name = "Die Casting Tooling"
  url = "/tooling/"
  weight = 36

[[main]]
  name = "Technical Blog"
  url = "/blog/"
  weight = 40

[[main]]
  name = "Request A Quote"
  url = "/contact/"
  weight = 50
