[[main]]
  name = "Inicio"
  url = "/es/"
  weight = 10

[[main]]
  name = "Fundicion de aluminio"
  url = "/es/aluminum-die-casting/"
  weight = 20

[[main]]
  name = "Fundicion de magnesio"
  url = "/es/magnesium-die-casting/"
  weight = 30

[[main]]
  name = "Colada semi-sólida"
  url = "/es/semi-solid-rheocasting/"
  weight = 32

[[main]]
  name = "Mecanizado CNC"
  url = "/es/cnc-machining/"
  weight = 34

[[main]]
  name = "Utillaje de moldeo"
  url = "/es/tooling/"
  weight = 36

[[main]]
  name = "Blog tecnico"
  url = "/es/blog/"
  weight = 40

[[main]]
  name = "Solicitar cotizacion"
  url = "/es/contact/"
  weight = 50
