[[main]]
  name = "ホーム"
  url = "/ja/"
  weight = 10

[[main]]
  name = "アルミダイカスト"
  url = "/ja/aluminum-die-casting/"
  weight = 20

[[main]]
  name = "マグネシウムダイカスト"
  url = "/ja/magnesium-die-casting/"
  weight = 30

[[main]]
  name = "半凝固レオキャスト"
  url = "/ja/semi-solid-rheocasting/"
  weight = 32

[[main]]
  name = "CNC加工"
  url = "/ja/cnc-machining/"
  weight = 34

[[main]]
  name = "ダイカスト金型"
  url = "/ja/tooling/"
  weight = 36

[[main]]
  name = "技術ブログ"
  url = "/ja/blog/"
  weight = 40

[[main]]
  name = "見積依頼"
  url = "/ja/contact/"
  weight = 50
