[[main]]
  name = "Home"
  url = "/"
  weight = 10

[[main]]
  name = "Aluminum Die Casting"
  url = "/aluminum-die-casting/"
  weight = 20

[[main]]
  name = "Magnesium Die Casting"
  url = "/magnesium-die-casting/"
  weight = 30

[[main]]
  name = "Technical Blog"
  url = "/blog/"
  weight = 40

[[main]]
  name = "Request A Quote"
  url = "/contact/"
  weight = 50